### ISSUE TITLE
Suggestions for improving the gaming experience

### ISSUE THREAD

**Issue by pipipupu-ui** [SoLegendary/ageofcraft#101]
Suggestions:

- Wizards should hit their target more often.
- Witches should heal without my participation, in my opinion.
- It would be possible to give all mobs two hitboxes: one small one for movement (so they don't get stuck in forests), the second normal one for enemy attacks.
- Add the ability to set multiple actions using the "shift+(key)" key combination, like in other strategy games like Warcraft or Dota.
- Add a game rule (if possible) that allows you to adjust the height of the blocks from which mobs will be allowed to jump (this may be useful for mapmakers).
- (Possibly) Make a separate smaller portal for piglins to infect, since it is hard to pull the infestation on small areas of the map.
- Add blockade methods, like a fence.
- Make it so that when you double-click the army selection button ("K"), the camera moves to it.
- Add the ability to select all units of the same type not only by double-clicking the mouse, but also by using "ctrl+(mouse click)".
- Make the fog of war in the form of a circle around the unit, and not as it is now in the form of chunks around the unit.
- Add a game rule allowing you to choose up to what height from the unit the fog of war spreads. Everything above this value will be in the fog (useful for mapmakers).

**Comment by IamAlittle** [comment]
This is a Github issues page meant for code bugs, not balance suggestions. I suggest you go to the discord server and chat there about it.  :))

**Comment by RealKomander** [comment]
> This is a Github issues page meant for code bugs, not balance suggestions. I suggest you go to the discord server and chat there about it. :))

The discord link on modrinth is invalid

**Comment by IamAlittle** [comment]
> > This is a Github issues page meant for code bugs, not balance suggestions. I suggest you go to the discord server and chat there about it. :))
> 
> The discord link on modrinth is invalid

https://discord.gg/uR6FWdUcw3
