### ISSUE TITLE
Fast camera movement in RTS mode cause rubberbanding

### ISSUE THREAD

**Issue by petepi3** [SoLegendary/ageofcraft#102]
Any fast movement of the camera in RTS mode cause the camera to rubberband back into previous position. This is happening both to the person hosting aswell as any clients that join.

Reproduction:
- Start a world with reignofnether
- Enable RTS mode
- Use alt+scroll wheen to zoom far out
- Use alt+mouse drag and perform a fast mouse movement

No other mods are installed besides reignofnether.
I am running an RTX 3090, Ryzen 5 7600X 6-Core with 30gb of ram alocated. 
I also tried changing view distance hoping this is a chunkloading issue, but result is the same on any setting the game allows me.

**Comment by ColinVaughn** [comment]
it's because there are rapid block changes, it needs more improvements but it's better than before.

**Comment by ColinVaughn** [comment]
can close should be fixed on latest

**Comment by SoLegendary** [comment]
Workaround if it still happens: install this: https://modrinth.com/mod/too-fast
