### ISSUE TITLE
I can not own my village!

### ISSUE THREAD

**Issue by Montgomery4545** [SoLegendary/ageofcraft#103]
@

The owners of villages were deleted. What should we do?
![2024-10-30_20-33-57](https://github.com/user-attachments/assets/d8aaa702-c307-4c27-966f-6a26befafc74)

**Comment by Montgomery4545** [comment]
Buildings are not clickable, villagers are not yours. How can we give back our villages?

**Comment by Montgomery4545** [comment]
![Uploading 2024-10-30_20-41-34.png…]()

**Comment by Montgomery4545** [comment]
I dont have some .dat files. Please, help me!!

**Comment by IamAlittle** [comment]
I only know that if the server suddenly shuts down and restarts, everyone will become a neutral unit

**Comment by SoLegendary** [comment]
Yes, this is a known issue and there is no known solution without heavily impacting performance by saving constantly, sorry
