### ISSUE TITLE
[BUG] Barracks construction stuck at 98% due to terrain constraints.

### ISSUE THREAD

**Issue by Patchouliys** [SoLegendary/ageofcraft#106]
The Barracks building for the Villager gets stuck at 98%. It was found that the last step needs **two grass** in front of the Barracks (shown in the image). But on some terrains, it’s impossible to place these grass.
![bug](https://github.com/user-attachments/assets/a9eea9a7-f360-4a27-9d3a-9ce3560170af)

**Comment by SoLegendary** [comment]
This has been fixed in 1.0.6a
