### ISSUE TITLE
Having Pehkui installed makes Piglin Faction mobs unable to spawn

### ISSUE THREAD

**Issue by Gormi124** [SoLegendary/ageofcraft#109]
**Steps to reproduce:**  
Create a modpack with Reign of Nether and Pehkui,
Launch the game and enter a world,
Try to spawn a Piglin Faction unit using the RTS menu or a spawn egg.

**Expected Behavior:**  
Units spawn as usual.

**Observed Behavior:**
Piglin units do not spawn at all. If the world had Piglin units before, they disappear. Units from the other two factions seem to work as intended.

**Comment:**
This is something I stumbled upon on accident and I assume it has a very low priority as Pehkui is not something you would expect this mod to be played with. I still find is curious, though, that only one of the three factions is affected.
According to [the error in the logs](https://github.com/user-attachments/files/17599820/error-with-pehkui.txt), this.targetGoal is null for the Piglin units, but that's really as far as I can comprehend it, hehe.

**Comment by SoLegendary** [comment]
Sorry, but i'm not troubleshooting issues that appear with other mods
