### ISSUE TITLE
[crash]; with new mod

### ISSUE THREAD

**Issue by IvoryJustie** [SoLegendary/ageofcraft#157]
[crash-2024-11-15_23.37.36-server.txt](https://github.com/user-attachments/files/17783510/crash-2024-11-15_23.37.36-server.txt)
other mod cause of crash:https://www.curseforge.com/minecraft/mc-mods/tensura-reincarnated

**Comment by SoLegendary** [comment]
Sorry, but the crash shows the source is from the other mod, so I can't help you here, you have to raise the issue with them
