### ISSUE TITLE
【BUG】1. The flag disappeared. 2. Human cavalry attacks buildings, but the riders keep shooting downwards.3. Particle effects disappear

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#158]
https://github.com/user-attachments/assets/f4e38499-0edd-4c30-a845-5959fb37a0f8

**Comment by IamAlittle** [comment]
Remove the texture pack, the flag will still disappear

**Comment by IamAlittle** [comment]
Version 1.0.8
It seems that the particle effects are no longer displayed, such as explosions and potion particles

**Comment by SoLegendary** [comment]
fixed in 1.0.11
