### ISSUE TITLE
【bug?】If there is a neutral faction, the player will crash the game when exiting the save file

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#162]
[crash-2024-11-17_22.02.10-server.txt](https://github.com/user-attachments/files/17790761/crash-2024-11-17_22.02.10-server.txt)

[crash-2024-11-17_21.22.38-server.txt](https://github.com/user-attachments/files/17790729/crash-2024-11-17_21.22.38-server.txt)

**Comment by SoLegendary** [comment]
Fixed in 1.0.9
