### ISSUE TITLE
【BUG】After berry infection, it cannot be collected as food

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#175]
![2RXDKDNP7L$E5~S@)_7X8ZF](https://github.com/user-attachments/assets/bb092c44-b744-44d7-b2d6-0b8c2877ffc4)
Suggest replacing Weeping Vines with Fungi

**Comment by SoLegendary** [comment]
fixed in 1.0.11, now becomes mushrooms
