### ISSUE TITLE
World generation stays stuck at 100%

### ISSUE THREAD

**Issue by MapperTV** [SoLegendary/ageofcraft#27]
Minecraft version: 1.19.2
Forge version: 43.4.0

When trying to create a new world, the game generates the world up to 100% and then stays stuck forever.

Logs: [latest.log](https://github.com/user-attachments/files/17350699/latest.log)
(no error are really visible, I just killed the game after waiting a few minutes)

I used the datapack you provided on CurseForge. Note that Minecraft considers this datapack to be made for an older version of Minecraft so that may be a clue?

Tried to generate multiple worlds, including one with the recommended seed 4756899154123723533.

**Comment by PROMETHIA-27** [comment]
I've been stuck on 100% as well.

Minecraft version: 1.19.2
Forge version: 43.4.0 or 43.2.21 or 43.1.0 (tested all)

Logs: [latest.log](https://github.com/user-attachments/files/17350927/latest.log)

I attempted to create a new survival world on the hard difficulty with the datapack from curseforge. The datapack also shows as old for me. No other tweaking of the default settings. Creative mode also did not work. Not starting with the datapack also did not work.

No other mods installed.

**Comment by Nytrez** [comment]
It works on Forge version 43.1.0. 
Tried 43.4.0 and didn't work.

**Comment by Coderchris842** [comment]
anybody made any progress?

**Comment by SoLegendary** [comment]
I've found the version in my code where it stopped working, currently
working on it
In the meantime im uploading a sample map for everyone to use (same seed as
the tutorial, just with the border and tutorial disabled)

**Comment by SoLegendary** [comment]
Fix is made, uploaded the new jar but approval may take some time since
this a new project.
In the meantime I uploaded a map with the same seed as the tutorial, but
with the tutorial disabled
https://www.curseforge.com/minecraft/mc-mods/reign-of-nether-rts-in-minecraft/download/5806860

**Comment by Coderchris842** [comment]
YEAH!!!! I WILL FINALLY BE ABLE TO PLAY!!!!

**Comment by SoLegendary** [comment]
New jar available: https://www.curseforge.com/minecraft/mc-mods/reign-of-nether-rts-in-minecraft/files/5806934

**Comment by Xlaits** [comment]
Just had this happen to me. Fresh install, latest forge 1.19.2, latest download from CurseForge.
