### ISSUE TITLE
mod can't be downloaded with prismc

### ISSUE THREAD

**Issue by Coderchris842** [SoLegendary/ageofcraft#28]
I use prism launcher, and I have to manually download the mod. This is really inconvenient so it would be nice if you changed that.

**Comment by SoLegendary** [comment]
Tbh, I didn't know that prism launcher existed until now, is there a process they have for making mods available via it?

**Comment by Coderchris842** [comment]
I don't know, maybe look around in curseforge settings?

**Comment by SoLegendary** [comment]
I set the curseforge project to allow 3rd party downloads, I assume that's what makes it available on other launchers, but I can't find it myself when I check prism launcher. It's possible it just takes a while for it to update, or it won't update there until I release a new version.

**Comment by PROMETHIA-27** [comment]
This is no longer true as of the recent patch to fix another issue, i was able to download it properly.

Edit: As for finding it, you have to have the right version and modloader set up and then search "reign", "reign of nether" seems to not work very well.
