### ISSUE TITLE
Starting a new match after another match results in negative resources

### ISSUE THREAD

**Issue by PROMETHIA-27** [SoLegendary/ageofcraft#29]
I played a match against a friend, and when we restarted on the same map we seemed to both have all negative resources, and this seems to cause the logic for resources to break and not check if we can afford things.

**Comment by SoLegendary** [comment]
When you say restart, do you mean using /rts-reset?

**Comment by PROMETHIA-27** [comment]
Ah, no, didn't realize there was a command for it- we just f12'd again to start a new match

**Comment by SoLegendary** [comment]
Regardless, still shouldn't have ever gone negative so i'll look into this later

**Comment by SoLegendary** [comment]
Oh I think this may just be a client desync issue - I forgot to wipe clientside resource counts after a reset, only did serverside

**Comment by SoLegendary** [comment]
Fixed as of 1.0.5
