### ISSUE TITLE
Units will pathfind onto and stand on top of magma even when not immune

### ISSUE THREAD

**Issue by PROMETHIA-27** [SoLegendary/ageofcraft#30]
This led to a good handful of my workers killing themselves while i wasn't looking as long as they were assigned to mine ore (since piglin ore turns into magma), which doesn't feel very good. I imagine you can slot in a penalty to walking on magma somewhere fairly easily? At least from what I've done with minecraft AI stuff.

**Comment by SoLegendary** [comment]
I can set a pathfinding malus to avoid it but it makes unit movement really awkward. I think I will just make piglin workers immune to magma by default, this way we can keep magma as a natural hazard that makes piglin bases unique while avoiding accidentally killing your workers off screen.

**Comment by PROMETHIA-27** [comment]
Sounds good to me!
