### ISSUE TITLE
Zombie villagers trample pumpkin farms and don't replant

### ISSUE THREAD

**Issue by PROMETHIA-27** [SoLegendary/ageofcraft#32]
Occasionally zombie villagers jump on the stems in the pumpkin farm and don't automatically replant them, leading to the farm slowly getting worse over time.

**Comment by Treyson757** [comment]
Dead Grunt stayed like this after I hit delete on a group of Grunts.
![image](https://github.com/user-attachments/assets/449497b5-51e2-464c-a057-3307f4fecd5d)

**Comment by PROMETHIA-27** [comment]
@Treyson757 You should make a new issue for this, rather than commenting it on an existing issue, makes it easier to keep track of

**Comment by Treyson757** [comment]
@PROMETHIA-27 Sorry about that, it's my first time using Github.

**Comment by SoLegendary** [comment]
I'll just disable crop trampling if it happens to the blocks of any farm building
