### ISSUE TITLE
Crash when selecting unit in multiple control groups

### ISSUE THREAD

**Issue by SzakiTheMaki** [SoLegendary/ageofcraft#40]
how to recreate:
1. put 1 or multiple unit(s) in 2 control groups (Ex. ctrl+1 and ctrl+2)
2. deselect unit(s) by pressing 0
3. Press the number used for the secondary control group
[crash-2024-10-16_20.06.18-client.txt](https://github.com/user-attachments/files/17400846/crash-2024-10-16_20.06.18-client.txt)
This may be a tiny issue, but there are examples in big armys when you want units to be selected in multiple control groups.

**Comment by MatheoMiller** [comment]
[crash-2024-10-16_14.56.34-client.txt](https://github.com/user-attachments/files/17402045/crash-2024-10-16_14.56.34-client.txt)
similar issue

**Comment by SoLegendary** [comment]
Fixed in 1.0.4 and 1.0.5
