### ISSUE TITLE
Iron Golems still hate Illagers

### ISSUE THREAD

**Issue by SzakiTheMaki** [SoLegendary/ageofcraft#41]
When you attack move an enemy/friendly/ or neutral unit with Iron Golems, Sometimes they can and will hit your own Illagers when walking with or trough them towards the attack moves target, then completly ignore said target and execute your own troop

how to recreate:
1. have a bunch of iron golems and illagers/pillagers in a group
2. attack move with the iron golems onto anything

some iron golems will ignore the target and instead commit to friendly fire

**Comment by SoLegendary** [comment]
I can't seem to recreate this myself. I have a few questions
1. Singleplayer or multiplayer?
2. Were there any regular villager (workers) in the group?
3. Does this happen when you attack move anywhere, or only onto enemies?

If possible, link a video

**Comment by SzakiTheMaki** [comment]
1. Just tried it in Brand new Singeplayer world to see if it still happens
2. No (if needed i will test that aswell later)
3. This is the tricky part. It doesn't happen if you attack move to a location, only if you attack move onto ANY target.

I will create a forum under bug reports on the discord server, with the same name and put the videos in there!
(Also if i find anything new i will rather post it there from now on, as other people might find solutions)

**Comment by SoLegendary** [comment]
Fixed in 1.0.5
