### ISSUE TITLE
suggestion: localization-friendly components

### ISSUE THREAD

**Issue by NumberSir** [SoLegendary/ageofcraft#43]
It's a pleasure to play such a creative and high-quality mod. 

However, the current language file covers only a small portion of the game's text. As a translator, I hope that future updates will gradually transition the hardcoded text in the source code to localizable content. 

Looking forward to seeing your mod continue to gain popularity among players :)

**Comment by SoLegendary** [comment]
Hi @NumberSir I've already got Promethia working on this

EDIT: sorry for the late response
