### ISSUE TITLE
Enabling programmer art causes the main menu title to become heavily distorted

### ISSUE THREAD

**Issue by PROMETHIA-27** [SoLegendary/ageofcraft#57]
Investigating a bit

**Comment by PROMETHIA-27** [comment]
Found someone who had this issue *without* enabling programmer art, so it's not strictly that datapack causing it. Not sure what might be the real cause though.

**Comment by SoLegendary** [comment]
Do keep in mind that I used a mixin for the title, and have no idea if theres a better way to do it https://github.com/SoLegendary/reignofnether/blob/1.19/src/main/java/com/solegendary/reignofnether/mixin/TitleScreenMixin.java

**Comment by SoLegendary** [comment]
Workaround found (see discord bug reports pinned post for known issues list)
