### ISSUE TITLE
Submit to Modrinth.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [SoLegendary/ageofcraft#59]
#### **Request**

Submit the mod package to the Modrinth platform.

#### **Rationale**

CurseForge is an impressive platform, but Modrinth is in many spheres considered to be its successor, *primarily* because:

1.	it's FOSS,
2.	all packages are always available via 3rd-party launchers, so https://github.com/SoLegendary/reignofnether/issues/60#issue-2600756378 cannot occur
3.	its moderation staff are significantly more consistent in their applications of its ToS, and
4.	the GUI is more consistent.

There is desire for this:

1. [`discord.com/channels/1294953087567663135/1294958724984737822/1297391432625295422`](https://discord.com/channels/1294953087567663135/1294958724984737822/1297391432625295422#:~:text=Yeah%2C%20I%20didn't%20get%20it%20cuz%20it's%20not%20in%20modrinth%20lol) states:

   > Yeah, I didn't get it cuz it's not in modrinth lol

5. [`discord.com/channels/1294953087567663135/1294957407180689500/1297297944659099758`](https://discord.com/channels/1294953087567663135/1294957407180689500/1297297944659099758#:~:text=Modrinth%20is%20a%20better%20app%20for%20doing%20mod%20profiles%20and%20has%20the%20same%20features%20than%20forge) states:

   > Modrinth is a better app for doing mod profiles and has the same features than forge

#### **(Lack of) Duplicates**

[`github.com/SoLegendary/reignofnether/issues?q=is%3Aissue+modrinth`](https://github.com/SoLegendary/reignofnether/issues?q=is%3Aissue+modrinth) returned 0 results at `2024-10-20T17:49:01+01:00`.

**Comment by PROMETHIA-27** [comment]
SoLegendary said in the discord that it's been uploaded to modrinth, they're just taking their time processing it.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SoLegendary/reignofnether/issues/59#issuecomment-2425120315

@PROMETHIA-27, do you have a URI to the message?

**Comment by PROMETHIA-27** [comment]
https://discord.com/channels/1294953087567663135/1294953087567663137/1296703859388846090

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SoLegendary/reignofnether/issues/59#issuecomment-2425125318

Thanks, @PROMETHIA-27. I'll close this issue when it's been published.

**Comment by SettingDust** [comment]
published

**Comment by RokeJulianLockhart** [comment]
Yep! Thanks. Per https://discord.com/channels/1294953087567663135/1294956403269570580/1297743476414349384, https://modrinth.com/mod/reign-of-nether-rts/version/1.0.5 is now available.
