### ISSUE TITLE
Unable to discover via API (via Prism Launcher).

### ISSUE THREAD

**Issue by RokeJulianLockhart** [SoLegendary/ageofcraft#60]
CurseForge permits developers to disable access to their content via the API. I believe that Reign of Nether has enabled this preference (probably inadvertently) because I am unable to discover it via https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.4:

> ![image](https://github.com/user-attachments/assets/d88cbce7-607b-491c-914b-216b53e236f8)

**Comment by PROMETHIA-27** [comment]
~~Firstly, you're looking in modpacks, this is a mod~~. Think I said that right before you edited the image. Secondly prism *does* get a bit confused, but if you just search "reign", not "reign of nether", it pops up more consistently.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SoLegendary/reignofnether/issues/60#issuecomment-2425165972

@PROMETHIA-27, I did notice that accompanying and remake packs solely appeared with merely “Reign”. However, I still scrolled past 50 mods and was unable to locate the official one - solely one remake and one add-on mod. Have you been able to?

**Comment by PROMETHIA-27** [comment]
Yep:
![image](https://github.com/user-attachments/assets/3f93704a-d070-48d0-8394-d3dd33251add)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SoLegendary/reignofnether/issues/60#issuecomment-2425169105

@PROMETHIA-27, my brother can see it on his installation — I still can't. Apologies for the superfluous issue, then. I'll ascertain what differs in my installation, in case another experiences it (with solely this mod, like I am).
