### ISSUE TITLE
Numeric shortcut keys crash when calling troops

### ISSUE THREAD

**Issue by YeLiShiEr** [SoLegendary/ageofcraft#62]
Ctrl-number-bound troops crash when called using shortcuts, especially when using shortcuts in the functional interface of the facility

In addition, I need to Chinese, thank you

Mod list

appleskin-forge-mc1.19-2.4.2.jar"
architectury-6.6.92-forge.jar"
cloth-config-8.3.134-forge.jar"
Controlling-forge-1.19.2-10.0+7.jar"
embeddium-0.3.18.1+mc1.19.2.jar"
entityculling-forge-1.6.1-mc1.19.2.jar"
ferritecore-5.0.3-forge.jar"
PhysicsModPro-1.19.2.jar"
ForgedAPI-0.1.0+1.19.2.jar"
ftb-library-forge-1902.4.1-build.236.jar"
ftb-ultimine-forge-1902.4.2-build.14.jar"
global_packs-forge-1.19.2-1.14.5_forge.jar"
I18nUpdateMod-3.5.5-all.jar"
InventoryProfilesNext-forge-1.19-1.10.11.jar"
kotlinforforge-3.12.0-all.jar"
lanserverproperties-1.9.1-forge.jar"
libIPN-forge-1.19-4.0.2.jar"
modernfix-forge-5.18.1+mc1.19.2.jar"
MouseTweaks-forge-mc1.19-2.23.jar"
ObsidianUI-forge-0.2.3+mc1.19.2.jar"
oculus-mc1.19.2-1.6.9.jar"
reforgium-1.0.12a.jar"
reignofnether-1.0.2.jar"
Searchables-forge-1.19.2-1.0.2.jar"
vaultpatcher-all-1.4.3+3.jar"
Xaeros_Minimap_24.5.0_Forge_1.19.1.jar"
XaerosWorldMap_1.39.0_Forge_1.19.1.jar"

**Comment by SoLegendary** [comment]
Should be fixed as of 1.0.5
