### ISSUE TITLE
Expand the limit of units to more than 100, get custom limit

### ISSUE THREAD

**Issue by unersame342** [SoLegendary/ageofcraft#71]
I tested the game with my brother and it is very good, but i notice that there is a limit to 100 units where building new villager house don't permit to get more slot of units, so i would like to know if it is possible to expand the slots of units in the settings of the mod or if it is not already implemented and it's a feature upcoming 

Great Work

The_killer_300

**Comment by SoLegendary** [comment]
Already implemented, use the cheatcode thereisnospoon X to set all players' max populations to X. You can also use foodforthought to ignore having to build houses at all.

Cheat codes only work for server ops.
