### ISSUE TITLE
Hell terrain cannot infect moss blocks, resulting in the inability to continue infection in the early stages

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#74]
Hell terrain cannot infect moss blocks
![B63O(~JJ4ZDTG)TRTT{ %%2](https://github.com/user-attachments/assets/eb4c57ea-3fb0-44cc-b1bf-4c9b5a600cc1)

**Comment by SoLegendary** [comment]
fixed in 1.0.6 beta
