### ISSUE TITLE
Cant open optifine/please make fabric

### ISSUE THREAD

**Issue by SmthingFunny** [SoLegendary/ageofcraft#75]
i have a toaster as a pc
and the mod doesnt work with optifine
if it doesnt work bcz of optifine fucks up mod visuals 
u can make it on fabric and sodium wont fuck it up 

please i wanna play it with friends but i have 2 fps 
minecraft without optimization mods is very bad so please make it 👍

**Comment by PROMETHIA-27** [comment]
Use embeddium instead. Not getting ported to fabric any time soon
