### ISSUE TITLE
The mod does not respect the locale settings

### ISSUE THREAD

**Issue by valokardin** [SoLegendary/ageofcraft#80]
I've tried all available translations in the mod, but in the end the mod doesn't want to follow the locale settings in the game and uses English.
![1](https://github.com/user-attachments/assets/389c20f3-d7ac-4287-9d92-5ad2161f045f)
![2](https://github.com/user-attachments/assets/5edd0aa7-f37d-4d00-a391-53060179c80e)

**Comment by PROMETHIA-27** [comment]
This is being worked on: https://github.com/SoLegendary/reignofnether/pull/70

At the moment I'm working on other things but once I get enough time I'm going to circle back and try to finish it up and get it merged. If you know how to use git/the commandline to clone and run `./gradlew runClient`, testing would be helpful, but if not then I'll get it done myself eventually.

**Comment by valokardin** [comment]
> This is being worked on: #70
> 
> At the moment I'm working on other things but once I get enough time I'm going to circle back and try to finish it up and get it merged. If you know how to use git/the commandline to clone and run , testing would be helpful, but if not then I'll get it done myself eventually.`./gradlew runClient`

I tried building a mod from this repository, but it gives an error when building it https://pastebin.com/3GhJKXwh

**Comment by SoLegendary** [comment]
There is also an issue even with completed translations where languages will not reload until a client restart

**Comment by SoLegendary** [comment]
Implemented localisation in 1.0.8, however you still need to restart your client to apply it
