### ISSUE TITLE
[BUG]Undead faction, unable to build laboratory

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#86]
Even if there is a cemetery in front of it, it cannot be built
![Uploading $JMCQNINLW_OGDB[[2L27DV.png…]()

**Comment by IamAlittle** [comment]
version:1.0.6R

**Comment by SoLegendary** [comment]
sorry, it's been reuploaded now

**Comment by IamAlittle** [comment]
> 抱歉，现已重新上传

Really? Still bug
