### ISSUE TITLE
【BUG】Building farmland in the light source block will prevent crop cultivation

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#87]
![QJU6}VB$WPI_TF(HNUE%A7A](https://github.com/user-attachments/assets/310839fc-089a-4bc8-9ef0-58c673549367)

https://github.com/user-attachments/assets/2704dd44-690d-446f-a2de-c38cf20a9b0a

**Comment by IamAlittle** [comment]
[](url)

**Comment by SoLegendary** [comment]
I've never seen this block before, is this a vanilla thing?

**Comment by TerwalEast** [comment]
> I've never seen this block before, is this a vanilla thing?

It is. The official implementation of invisible light source since 1.17.

**Comment by IamAlittle** [comment]
> I've never seen this block before, is this a vanilla thing?

The wiki says that light blocks can hinder plant growth, which should refer to pumpkins

**Comment by AlexanderwithaA** [comment]
It does more than just prevent farming, here are some other bugs with it https://discord.com/channels/1294953087567663135/1302588587728044072

**Comment by SoLegendary** [comment]
fixed in 1.0.11
