### ISSUE TITLE
Mounted pillager AI glitch upon attacking buildings

### ISSUE THREAD

**Issue by TerwalEast** [SoLegendary/ageofcraft#88]
If you order a pillager on a ravager to attack buildings while in close proximity with targeted building, the range attack ai may glitch and keeps firing directly downwards on ground (or attacking the mount?) even after moved away from the said building. Usually result in quick death of rider. Tested on 1.0.6.

**Comment by IamAlittle** [comment]
When I was playing, Ravager's movement became difficult to control when he encountered a building after being ridden

**Comment by TerwalEast** [comment]
Update: Actually it's not just when attacking buildings. All mounted pillager AI is glitchy at the moment (1.0.6a) that they draw argo at each other upon friendly fire.

**Comment by larrymaple** [comment]
Mounted pillagers also use their mortar attack unprompted (as opposed to with an ability button), leading to some [extreme silliness](https://files.catbox.moe/etly6y.mp4) (and friendly fire).

**Comment by SoLegendary** [comment]
Fixed in 1.0.7
