### ISSUE TITLE
Skulk Spreader crashed game upon use in multiplayer server

### ISSUE THREAD

**Issue by KingGregar** [SoLegendary/ageofcraft#90]
[crash-2024-10-28_15.37.04-server.txt](https://github.com/user-attachments/files/17548520/crash-2024-10-28_15.37.04-server.txt)
  This is the report of the issue, I hope it uploads

**Comment by KingGregar** [comment]
not much else I can add, as the issue is not something I would know how to fix or adjust to making working.

**Comment by SoLegendary** [comment]
Have you tried this in 1.0.6a?

**Comment by KingGregar** [comment]
I downloaded the mod before you released that patch, so I just had bad timing XD
