### ISSUE TITLE
【 BUG 】 F12 can still be used in adventure mode, but it will fall from a high place after switching

### ISSUE THREAD

**Issue by IamAlittle** [SoLegendary/ageofcraft#97]
After resurrection, you can still see your own model on the ground and drag the perspective
version：1.0.6beta、1.0.6a
![HH@$O`WKDBQEHJ5ETB4SS 7](https://github.com/user-attachments/assets/d24a2427-b915-4dc1-9c84-579e626d6e07)

https://github.com/user-attachments/assets/663e80ee-213f-475f-844d-1dcf232bcf43

**Comment by SoLegendary** [comment]
Fixed in 1.0.7
